### ISSUE TITLE
Run pretrained models on testing data

### ISSUE THREAD

**Issue by chiffonng** [IRMVLab/RegFormer#11]
Hi authors, thanks for your wonderful work! 

I wish to run just the inference of pretrained models on testing data before running it on my own data, but I'm not sure how to specify checkpoint path for the argument `--ckpt`. 

**The models downloaded and unzipped from [Google Drive](https://drive.google.com/drive/folders/1epQUIxG4wIg2yJu7kxArrwOmE0B24OeV) do not have `.pt` or `.pth` files for saved Pytorch checkpoints**. 

The unzipped directory for one model has the following format:

```
archive
|------ data/
|---------------- 0
|---------------- 1
|---------------- ... 2k more files 
|------ data.pkl
|------ version
```

Given this, what path/file should I assign to `--ckpt` or the argument in `configs.py`?

Sorry if this is a beginner question! I'm new to robotics research and Pytorch in general.

**Comment by liujiuming123** [comment]
Hi, pretrained model is speficied by the parameter 'ckpt' in configs.py file. And you can replace the parameter name with the pretrained checkpoint's name we provided.

**Comment by chiffonng** [comment]
@liujiuming123 Is there perhaps any update on this?

**Comment by liujiuming123** [comment]
Hi! There is no need to unzip it. Just download the file with the ending of .pth.tar and copy this on --ckpt.
![1719126542883](https://github.com/IRMVLab/RegFormer/assets/118814632/94b5771c-ae94-4e34-a0a5-38864385f537)

**Comment by chiffonng** [comment]
Thank you, the model checkpoints can be loaded now. I run into other issues but I will look into them first.
