### ISSUE TITLE
Question about the test results of pretrained model

### ISSUE THREAD

**Issue by yuxuanfanOrion** [IRMVLab/RegFormer#15]
Thanks for doing such a great job and for providing the network code.

I meet some problems when I running the pretrained model for testing. The registration recall of the 08/09/10 list are 12%/0.25%/8.65%, they are way different from the paper. Is this my problem?

**Comment by liujiuming123** [comment]
I think maybe something goes wrong with your GPUs or environments. We have checked and re-runned the code for many times to guarantee the reproductivity.

**Comment by yuxuanfanOrion** [comment]
> I think maybe something goes wrong with your GPUs or environments. We have checked and re-runned the code for many times to guarantee the reproductivity.我认为您的 GPU 或环境可能出了问题。我们对代码进行了多次检查和重新运行，以保证重现性。

Sorry it's my fault and I try it again, finding your pretrained model is correct.
