### ISSUE TITLE
cpu only

### ISSUE THREAD

**Issue by darkdelting** [IRMVLab/RegFormer#16]
I want cpu only to test pretrained model, but pointnet and  CUDA-based KNN searching c++lib need change.
if i use https://github.com/yanx27/Pointnet_Pointnet2_pytorch/tree/master cpu only modle ， can it replace the current pointnet ?

**Comment by liujiuming123** [comment]
Since our feature extraction part follows the same pattern like EfficientLO (TPAMI22), they utilize CUDA for point feature subtraction in parallel. Maybe using cpu is not a good choice I think, mostly for efficiency consideration.

**Comment by darkdelting** [comment]
Thank you for your answer!!!  but cpu is cheap ~^ ^~
