### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for Model

### ISSUE THREAD

**Issue by mochan-shs** [IRMVLab/RegFormer#2]
Thanks a lot for sharing pretrained model. When I was loading the model, I encountered a problem, which was caused by a mismatch between the model and the pretrained model. Could you please provide the model code corresponding to the pretrained model?

**Comment by liujiuming123** [comment]
Thanks for your suggestion. For simplicity, some unused initialization layers were removed but still remained in the checkpoints. We have uploaded the file 'regformer_model.py' , and you can download it again.
