### ISSUE TITLE
Cylindrical vs spherical projection

### ISSUE THREAD

**Issue by gfkri** [IRMVLab/RegFormer#3]
Hello,

thank you for your work and for sharing your code. Anyway, is there a chance, that you mixed up cylindrical with spherical projection? Imho given a cylindrical projection, (Cartesian LiDAR) coordinates are projected onto a cylinder by simply computing azimuth and maintaining z (i.e. z_cylindrical = z_cartesian). You on the other hand compute a position on a sphere (by computing azimuth and inclination), which imho makes much more sense, since a spherical projection is inherent to most LiDARs (respectively its discretized version, the "range image"). E.g. see [1]

Thank you very much in advance.
BR
Georg

[1] Fan et al.; "RangeDet: In Defense of Range View for LiDAR-based 3D Object Detection"; ICCV 2021

**Comment by liujiuming123** [comment]
Thank you for your kindly advice! Our original cylindrical projection has this limitation, where both KITTI and NuScenes datasets are captured by mechanical rotating LiDAR. We also think the spherical projection has more flexibility and leave how to mix them as our future work. Anyway, thanks for your suggestion and I remenber that we have talked at this idea at the ICCV conference.
