### ISSUE TITLE
neighbor_idx out of bounds

### ISSUE THREAD

**Issue by zlynpu** [IRMVLab/RegFormer#6]
When I was debugging, I found that neighbor_idx would become garbled as shown in the picture. What is the reason for this?
![image](https://github.com/IRMVLab/RegFormer/assets/103632029/7d123434-b09e-43fe-b029-57e92f302c6f)
This is in lines 549~554 of conv_util.py.
And I would like to ask what is the difference between fused_conv_select_k and fused_conv_select_k_add in ops_torch.
Thank you for your reply！

**Comment by zlynpu** [comment]
My environment is CUDA11.3, pytorch1.10.0, and the device is NVIDIA RTX3090, which is almost the same as in the README.

**Comment by liujiuming123** [comment]
We haven't met the same problem that neighbor idx is out of bounds as stated. It is quite confusing. The environment is okay and 'fused_conv_select_k_add' is another version which we didn't use here.  We only use 'fused_conv_select_k' for CUDA-based KNN searching.

**Comment by zlynpu** [comment]
> We haven't met the same problem that neighbor idx is out of bounds as stated. It is quite confusing. The environment is okay and 'fused_conv_select_k_add' is another version which we didn't use here. We only use 'fused_conv_select_k' for CUDA-based KNN searching.

Okay, thanks anyway

**Comment by liujiuming123** [comment]
We found that the index setting inside the CUDA operator was wrong, and have corrected it now. You can try to compile them again.

**Comment by zlynpu** [comment]
> We found that the index setting inside the CUDA operator was wrong, and have corrected it now. You can try to compile them again.

Ok now the problem is solved, thank you very much！
