### ISSUE TITLE
Regarding Training Time on nuScenes Dataset

### ISSUE THREAD

**Issue by hankeceli** [IRMVLab/RegFormer#7]
Hello,

I appreciate the openness in sharing your codebase. I am considering making some modifications to the source code for educational purposes. Could you kindly provide insights into the training time required for your model on the nuScenes dataset?

In the paper, it was mentioned that training was conducted on a single Titan RTX. I would appreciate it if you could reiterate the hardware specifications for clarity. In the README.md file, there is a reference to RTX 3090, which is not explicitly mentioned in the paper. Could you please provide clarification on the hardware used during your experiments?

Thank you for your assistance.

**Comment by liujiuming123** [comment]
Sure! We conducted experiments on both devices before. However, we recommend to use the RTX 3090 for training. Also, training on nuscenes dataset will cost about one hour for one epoch since the dataset in nuscenes is much larger than KITTI.
